using System;
using UnityEngine;
using UnityEngine.SceneManagement;

public enum SceneList : int
{
    Title,
    Car_Selection,
    In_Game,
    Result,
    Ranking
}

public class LevelManager : MonoBehaviour
{
    //シングルトン
    public static LevelManager Instance;

    public SceneList CurrentScene;

    public SceneList InitScene = SceneList.Title;

    public GameObject Car { get; set; } = null;

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(this.gameObject);
            return;
        }

        Instance = this;
        DontDestroyOnLoad(this.gameObject);

        //シーン更新伴う処理
        SceneManager.sceneUnloaded += OnSceneUnloaded;
        SceneManager.sceneLoaded += OnSceneloaded;
    }

    private void OnSceneUnloaded(Scene _CurrentScene)
    {

    }

    private void OnSceneloaded(Scene _CurrentScene, LoadSceneMode _mode)
    {
        //違うシーンに違う処理をする
        switch (ConvertSceneNameToEnum(_CurrentScene.name))
        {
            case SceneList.Title:
                Debug.Log("Titleに入た");
                break;
            case SceneList.Car_Selection:
                Debug.Log("Selectionに入た");
                break;
            case SceneList.In_Game:
                Debug.Log("InGameに入た");
                break;
            case SceneList.Result:
                Debug.Log("Resultに入た");
                break;
            case SceneList.Ranking:
                Debug.Log("Rankingに入た");
                break;
        }
    }

    private void Start()
    {

        CurrentScene = InitScene;
    }
    //シーン遷移判定
    public void LoadScene(SceneList _NextSceneName)
    {
        switch (_NextSceneName)
        {
            case SceneList.Title:
                SceneManager.LoadScene("Title");
                break;
            case SceneList.Car_Selection:
                SceneManager.LoadScene("Selection");
                break;
            case SceneList.In_Game:
                SceneManager.LoadScene("InGame");
                break;
            case SceneList.Result:
                SceneManager.LoadScene("Result");
                break;
            case SceneList.Ranking:
                SceneManager.LoadScene("Ranking");
                break;
        }
        CurrentScene = _NextSceneName;
    }

    private void Update()
    {
        if (Input.anyKeyDown && CurrentScene == SceneList.Title)
        {
            LoadScene(SceneList.Car_Selection);
        }

        if (Input.GetKeyDown(KeyCode.Return) && CurrentScene == SceneList.Car_Selection)
        {
            LoadScene(SceneList.In_Game);
        }

        if (Input.anyKeyDown && CurrentScene == SceneList.Result)
        {
            LoadScene(SceneList.Title);
            PlayerDataManager.Instance.Save();
        }
    }

    public SceneList GetCurrentScene()
    {
        return CurrentScene;
    }

    //
    private SceneList ConvertSceneNameToEnum(string sceneName)
    {
        return sceneName switch
        {
            "Title" => SceneList.Title,
            "Selection" => SceneList.Car_Selection,
            "InGame" => SceneList.In_Game,
            "Result" => SceneList.Result,
            "Ranking" => SceneList.Ranking,
            "InGame_ForDebug"=>SceneList.In_Game,   
            _ => throw new ArgumentOutOfRangeException(nameof(sceneName), $"不明なシーン名: {sceneName}")
        };
    }
}
